### ISSUE TITLE
docker-compose linux 内容错误,无法启动

### ISSUE THREAD

**Issue by paopjian** [tencentmusic/fab#2]
使用network_mode: host就不应该再分配port
```
Recreating e6dc85f09a89_docker_redis_1 ... 

ERROR: for e6dc85f09a89_docker_redis_1  "host" network_mode is incompatible with port_bindings

ERROR: for redis  "host" network_mode is incompatible with port_bindings
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 702, in up
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/project.py", line 688, in do
  File "compose/service.py", line 581, in execute_convergence_plan
  File "compose/service.py", line 503, in _execute_convergence_recreate
  File "compose/parallel.py", line 108, in parallel_execute
  File "compose/parallel.py", line 206, in producer
  File "compose/service.py", line 496, in recreate
  File "compose/service.py", line 615, in recreate_container
  File "compose/service.py", line 334, in create_container
  File "compose/service.py", line 941, in _get_container_create_options
  File "compose/service.py", line 1073, in _get_container_host_config
  File "docker/api/container.py", line 598, in create_host_config
  File "docker/types/containers.py", line 339, in __init__
docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
[25458] Failed to execute script docker-compose
```

**Comment by data-infra** [comment]
不能使用host模式，不然多个服务之间不方便访问

**Comment by paopjian** [comment]
可是你们的本地开发连readme都跑不通吗,还是限定mac环境?

**Comment by data-infra** [comment]
你如果开发cube-studio，可以直接本地启动cube-studio。
